### ISSUE TITLE
Add ability to select stanzas for `cabal-plan dot` command

### ISSUE THREAD

**Issue by chshersh** [haskell-hvr/cabal-plan#24]
I want to see dependencies of my package. But when I execute `cabal-plan dot` command I see dependencies of `test-suite` as well. It would be really nice to have an ability to see dependencies only for library.

**Comment by phadej** [comment]
Workaround: `cabal new-build --disable-tests --dry` before `cabal-plan dot`

**Comment by ChShersh** [comment]
Another workaround: use `gvpr` with the script to extract subgraph starting from given vertex:

* https://stackoverflow.com/a/50842371/2900502

**Comment by mitchellwrosen** [comment]
Similar: graphing dependencies of only a single package in a multi-package project.

**Comment by mitchellwrosen** [comment]
I think #41 covers this
