### ISSUE TITLE
topograph not in Hackage

### ISSUE THREAD

**Issue by juhp** [haskell-hvr/cabal-plan#31]
I am probably missing something but topograph is not in Hackage.
So one is not meant to `cabal install topograph`?
I was trying to build cabal-helper (which now needs cabal-plan) for Fedora...

**Comment by phadej** [comment]
topograph is internal lib

**Comment by phadej** [comment]
i.e.

https://github.com/haskell-hvr/cabal-plan/blob/84a5e6d529670ceea4df88615fa8388444c45335/cabal-plan.cabal#L89-L100

**Comment by juhp** [comment]
Thanks got it, doh

**Comment by hvr** [comment]
@juhp do you have a use-case for using topograph as a library in your code that would benefit from releasing `topograph` as a library in its own right on Hackage?

**Comment by juhp** [comment]
Not at this time - I was partly curious about the library and my Fedora packaging tool doesn't catch internal libraries yet...
