### ISSUE TITLE
You asked to install executables, but there are no executables in target: cabal-plan. 

### ISSUE THREAD

**Issue by Mikolaj** [haskell-hvr/cabal-plan#59]
Hi! After the 0.7 update I'm getting:

Installing library in /home/travis/.cabal/store/ghc-8.2.2/incoming/new-7485/home/travis/.cabal/store/ghc-8.2.2/aeson-1.5.1.0-6a0a95190144ea25bf638a1a4453f043656f0c1d0e1ad60d05ecb479b720e4cd/lib

Configuring library for cabal-plan-0.7.0.0..

Preprocessing library for cabal-plan-0.7.0.0..

Building library for cabal-plan-0.7.0.0..

[1 of 1] Compiling Cabal.Plan       ( src/Cabal/Plan.hs, dist/build/Cabal/Plan.o )

Installing library in /home/travis/.cabal/store/ghc-8.2.2/incoming/new-7485/home/travis/.cabal/store/ghc-8.2.2/cabal-plan-0.7.0.0-74b1b9f71f8b69558f21ca9bcde695c1813ec431eaf9f5f9f6dd216aac0b1026/lib

Warning: You asked to install executables, but there are no executables in target: cabal-plan. Perhaps you want to use --lib to install libraries instead.

And similarly for many other setups: 

https://travis-ci.org/github/AllureOfTheStars/Allure/builds/691207997

**Comment by phadej** [comment]
Add a `--constraint='cabal-plan +exe'` to your `v2-install` line. It will tell what's wrong.

Probably some constraint making that automatic flag go off, by forcing it that way it will stay on. So either things just works (solver picks different versions), or then it tells what's wrong.

The local project affects `cabal v2-install`. You could also use `cabal install --ignore-project`, IIRC that is in `cabal-install-3.2`.

**Comment by Mikolaj** [comment]
Great, it works with the constraint, thank you! Indeed, a cabal.project.local was constructed before the invocation, so possibly the culprit. Closing.

**Comment by Mikolaj** [comment]
Related, but probably a bug in cabal proper (let me know and I'd open a ticket): internal error in InstallPlan.completed: not in configured state: Installed

https://travis-ci.org/github/AllureOfTheStars/Allure/jobs/693560965#L394

It works fine in dozes of very similar job with cabal 3.2 and fail in only this one, consistently.
