### ISSUE TITLE
cabal-plan-0.6.2.0 : please revise bounds to allow these-1.1

### ISSUE THREAD

**Issue by alanz** [haskell-hvr/cabal-plan#60]
There is a revision on cabal-plan-0.7.0.0 to extend the acceptable range for these to be

```
, these          ^>= 1 || ^>=1.1
```

Please apply this to version 0.6.2.0 too.

Context: the build using cabal of `cabal-plan-0.6.2.0` uses `these-1.1`, but stack complains. Trying to bump resolvers for haskell-ide-engine.

**Comment by alanz** [comment]
ping @phadej

**Comment by phadej** [comment]
I'm not really sure what the problem, but here you go: https://hackage.haskell.org/package/cabal-plan-0.6.2.0/revisions/
