### ISSUE TITLE
GHC 9 support?

### ISSUE THREAD

**Issue by kozross** [haskell-hvr/cabal-plan#72]
This is blocking at least [this](https://github.com/phadej/cabal-extras/issues/78), which transitively blocks [this](https://github.com/kozross/text-ascii/issues/18).

**Comment by ekmett** [comment]
This is actively blocking me as well.

**Comment by andreasabel** [comment]
The latest release compiles fine with GHC 9.0, even though the https://hackage.haskell.org/package/cabal-plan-0.7.2.1/changelog does not mention it.

@kozross Is the issue resolved for you?

**Comment by kozross** [comment]
@andreasabel I ended up working around it.

**Comment by andreasabel** [comment]
I think this issue can be closed.
