### ISSUE TITLE
`cabal-plan dot` for internal dependencies only

### ISSUE THREAD

**Issue by peterbecich** [haskell-hvr/cabal-plan#84]
I believe `cabal-plan dot` generates a visualization of all internal and external dependencies.

Can a visualization restricted to internal dependencies be implemented?

Internal-only dependency visualization is a useful feature of Stack: https://docs.haskellstack.org/en/stable/dependency_visualization/

Thank you

**Comment by phadej** [comment]
For example take [optics repository](https://github.com/well-typed/optics)

```

**Comment by peterbecich** [comment]
Thanks
