### ISSUE TITLE
License report not working (broken macro condition)

### ISSUE THREAD

**Issue by andys8** [haskell-hvr/cabal-plan#87]
The latest version 0.7.2.2 seems to have the license report broken.

`Cabal` was replaced by `Cabal-syntax`. 

https://github.com/haskell-hvr/cabal-plan/commit/9f8f3f48c2426918a828c11b534a02391e61c4da#diff-23e8e99cc253e60e2a102314196134f5c41bb53f9da01124018798e371228bb5R130

But there are macros checking for the minimum - and if defined at all - `Cabal` version:

https://github.com/haskell-hvr/cabal-plan/blob/b3982f3ce48d8b3b2dc5cff11b719debbaac6e70/src-exe/LicenseReport.hs#L12

These are always wrong and we run into this error all the time.

https://github.com/haskell-hvr/cabal-plan/blob/b3982f3ce48d8b3b2dc5cff11b719debbaac6e70/src-exe/LicenseReport.hs#L295

**Comment by phadej** [comment]
Fixed in #88 and #89
