### ISSUE TITLE
Support XDG cabal config location

### ISSUE THREAD

**Issue by fgaz** [haskell-hvr/cabal-plan#92]
```
$ cabal-plan license-report mypackage
cabal-plan: /home/fgaz/.cabal/config: withBinaryFile: does not exist (No such file or directory
```

**Comment by phadej** [comment]
This is an issue in `cabal-install-parsers`. A link to docs describing new cabal config discovery logic would be helpful.

**Comment by fgaz** [comment]
https://github.com/haskell-CI/haskell-ci/issues/655

**Comment by fgaz** [comment]
Workaround: set `store-dir` explicitly in the cabal config file, then:

```
CABAL_CONFIG=~/.config/cabal/config cabal-plan license-report mypackage
```
